version: "3"
services:
  webserver:
    build: ""
    container_name: "webserver"
    ports:
      - 80:80
    volumes:
      - ./html/index.html:/usr/share/nginx/html/index.html
      - ./style/style.css:/usr/share/nginx/html/style.css